Document: guix
Title: Debian guix Manual
Author: <insert document author here>
Abstract: This manual describes what guix is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/guix/guix.sgml.gz

Format: postscript
Files: /usr/share/doc/guix/guix.ps.gz

Format: text
Files: /usr/share/doc/guix/guix.text.gz

Format: HTML
Index: /usr/share/doc/guix/html/index.html
Files: /usr/share/doc/guix/html/*.html
